config/routes.rb
Rails.application.routes.draw do
  resources :all_results, only: [:index]
  resources :squadrons, only: [:index, :show]
  resources :soldiers, only: [:index, :show]
  resources :planets, only: [:index, :show]
  resources :categories, only: [:index]
  resources :rebels, only: [:index]
  resources :about, only: [:index]

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'rebels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :soldier
  belongs_to :planet

  validates :operation_code, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
    has_many :assignments
    has_many :soldiers, through: :assignments

    validates :name, presence: true  
end

app/models/soldier.rb
class Soldier < ApplicationRecord
  belongs_to :squadron

  has_many :assignments
  has_many :planets, through: :assignments

  validates :name, presence: true
  validates :age, numericality: { only_integer: true }
end

app/models/squadron.rb
class Squadron < ApplicationRecord
    has_many :soldiers

    validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/all_results_controller.rb
class AllResultsController < ApplicationController
  def index
    @squadrons = Squadron.all
    @planets = Planet.all
    @soldiers = Soldier.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
    @soldiers = @planet.soldiers
  end
end

app/controllers/rebels_controller.rb
class RebelsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def results
    @squadrons = Squadron.where('name LIKE ?', "%#{params[:q]}%")
    @planets = Planet.where('name LIKE ?', "%#{params[:q]}%")
    @soldiers = Soldier.where('name LIKE ?', "%#{params[:q]}%")
  end
end

app/controllers/soldiers_controller.rb
class SoldiersController < ApplicationController
  def index
    @soldiers = Soldier.all
  end

  def show
    @soldier = Soldier.find(params[:id])
    @planets = @soldier.planets
  end
end

app/controllers/squadrons_controller.rb
class SquadronsController < ApplicationController
  def index
    @squadrons = Squadron.all
  end

  def show
    @squadron = Squadron.find(params[:id])
    @soldiers = @squadron.soldiers
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/all_results_helper.rb
module AllResultsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/rebels_helper.rb
module RebelsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/soldiers_helper.rb
module SoldiersHelper
end

app/helpers/squadrons_helper.rb
module SquadronsHelper
end

app/views/about/index.html.erb
<h2>About This Project</h2>
<p>
    This project uses the Faker gem to create a Star Wars related database. It includes 4 tables.
</p>
<p>
    The first table consists of the squadrons, containing the name of the squadron by using the StarWars gem.
</p>
<p>
    The second table consists of Rebel soldiers, containing randomly generated names, by using the FunnyName gem 
    (because Star Wars characters have funny names), as well as randomly generated ages, by using the Number gem.
</p>
<p>
    The third table consists of the planets, containing the name of the planet by using the StarWars gem.
</p>
<p>
    Finally, the fourth table contains assignments from when soldiers served an operation on them. 
    It includes the soldier, the planet they were assigned to at the time, 
    along with an operation code that consists of a species from the StarWars gem and a number from the Number gem.
</p>
<p>
    This allows each Soldier page to contain all the planets they have previously been assigned on, 
    as well as allow the Planet page to contain all the soldiers that have previously been assigned on it. 
    A planet can have many soldiers having been stationed with it, through assignments. 
    A soldier can have served on many planets, through assignments. 
    A soldier can only currently serve with one squadron. A squadron can have many soldiers serving on it. 
    An assignment can have only one soldier and one planet.
</p>
<p>
    Below is an ERD, containing the layout of the tables.
</p>
<%= image_tag "erd.PNG", alt: "ERD" %>

app/views/all_results/index.html.erb
<h2>All Results</h2>
<h3>Squadrons</h3>
<ul>
  <% @squadrons.each do |squadron| %>
    <li>
      <%= link_to squadron.name, squadron %>
    </li>
  <% end %>
</ul>
<h3>Planets</h3>
<ul>
  <% @planets.each do |planet| %>
    <li>
      <%= link_to planet.name, planet %>
    </li>
  <% end %>
</ul>
<h3>Soldiers</h3>
<ul>
  <% @soldiers.each do |soldier| %>
    <li>
      <%= link_to soldier.name, soldier %>
    </li>
  <% end %>
</ul>

app/views/categories/index.html.erb
<h2>Select a category that you wish to view.</h2>
<nav>
    <ul>
        <li><%= link_to 'All Results', all_results_path %></li>
        <li><%= link_to 'Squadrons', squadrons_path %></li>
        <li><%= link_to 'Planets', planets_path %></li>
        <li><%= link_to 'Soldiers', soldiers_path %></li>
    </ul>
</nav>

app/views/rebels/index.html.erb
<h2>Home</h2>
<h3>Please select one of the navigation links at the top.</h3>

app/views/rebels/show.html.erb
<h1>Rebels#show</h1>
<p>Find me in app/views/rebels/show.html.erb</p>

app/views/search/index.html.erb
<h2>Search</h2>

<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<% if @squadrons.empty? && @planets.empty? && @soldiers.empty? %>
    <h2>No results were found.</h2>
<% else %>    
    <h2>Total Results: <%= @squadrons.size + @planets.size + @soldiers.size %></h2>
    <% if @squadrons.empty? %>
        <h3>No squadrons were found.</h3>
    <% else %>
        <h3>Squadron Results: <%= @squadrons.size %></h3>
        <ul>
        <% @squadrons.each do |squadron| %>
            <li>
            <%= link_to squadron.name, squadron %>
            </li>
        <% end %>
        </ul>
    <% end %>
    <% if @planets.empty? %>
        <h3>No planets were found.</h3>
    <% else %>
        <h3>Planet Results: <%= @planets.size %></h3>
        <ul>
        <% @planets.each do |planet| %>
            <li>
            <%= link_to planet.name, planet %>
            </li>
        <% end %>
        </ul>
    <% end %>
    <% if @soldiers.empty? %>
        <h3>No soldiers were found.</h3>
    <% else %>
        <h3>Soldier Results: <%= @soldiers.size %></h3>
        <ul>
        <% @soldiers.each do |soldier| %>
            <li>
            <%= link_to soldier.name, soldier %>
            </li>
        <% end %>
        </ul>
    <% end %>
<% end %>